### ISSUE TITLE
adding cookie

### ISSUE THREAD

**Issue by rikaismine** [Myrkie/BoothDownloader#20]
i cannot download the files because whenever i try and add the cookie, i cant edit anythign on the json file

**Comment by Myrkie** [comment]
if you are having issues manually setting the cookie then the cookie could be wrong the fallback in this case is to clear the cookie to continue operation, you can do it automatically via the tamper monkey automation setup with the [companion user script](https://github.com/Myrkie/BoothDownloader?tab=readme-ov-file#automatic-setup) make sure you install Tamper Monkey Beta and the script aswell as the URL protocol handler, after that navigate to the orders page of [booth.pm](https://manage.booth.pm/orders) and click the token button at the top.
![image](https://github.com/user-attachments/assets/fda93af7-9a10-4509-bcbd-f61ce16612b1)

**Comment by rikaismine** [comment]
hi when i click on token nothing happens

**Comment by Myrkie** [comment]
> hi when i click on token nothing happens

did you follow step 2 when installing the handler? https://github.com/Myrkie/BoothDownloader?tab=readme-ov-file#automatic-setup

**Comment by rikaismine** [comment]
![Screenshot 2024-09-14 083922](https://github.com/user-attachments/assets/80125437-938d-4490-8479-cdfa7af8d1c7)
been there done that, could you just maybe give me a zip file of the model?

**Comment by Myrkie** [comment]
> been there done that, could you just maybe give me a zip file of the model?

but you must purchase the model yourself, booth downloader only downloads content you have paid for or content that has been marked as free for download on the website, we are only a better downloader.
