### ISSUE TITLE
Can someone send me a file to a certain boothmodel

### ISSUE THREAD

**Issue by arietteVTENID** [Myrkie/BoothDownloader#21]
I've tried over and over and it's just not working at this point I give so if someone could download this file I could pay you some money or something I just need this file 【完全live2dモデル】battle maid NVPU 20+exp（VtubeStudio対応） | 貓橋 Azusa #booth_pm https://nekohashiazusa.booth.pm/items/5256580

**Comment by DubyaDude** [comment]
This only downloads items you have purchased or is free, if you do not have it purchased we can not help you obtain the download.

**Comment by Myrkie** [comment]
as stated above this application only downloads paid content, it is not possible to download content you do not own.
