### ISSUE TITLE
new updates ?

### ISSUE THREAD

**Issue by XenmZV** [Myrkie/BoothDownloader#4]
Any more updates coming or is this project dead

**Comment by Myrkie** [comment]
project is still alive, I only update it when im told about it failing with its functions, as currently it is still working as intended, downloading items from booth, ive only had to upgrade the graphics in recent months to support interface changes for grabbing cookies.

**Comment by XenmZV** [comment]
> project is still alive, I only update it when im told about it failing with its functions, as currently it is still working as intended, downloading items from booth, ive only had to upgrade the graphics in recent months to support interface changes for grabbing cookies.

Nice, thanks for quick response too

**Comment by Myrkie** [comment]
> > project is still alive, I only update it when im told about it failing with its functions, as currently it is still working as intended, downloading items from booth, ive only had to upgrade the graphics in recent months to support interface changes for grabbing cookies.
> 
> Nice, thanks for quick response too

the project is very much in maintenance mode as is, im not planning to add anymore features only planning to keep current ones working, currently the only changes I may make in the future is a rewrite to the partner program [BoothWatcher](https://github.com/Myrkie/BoothWatcher), and possibly rewriting the orders page parser to be more robust.

**Comment by Myrkie** [comment]
feel free to create a new issue or comment on this one in the future if any issues with the software occur, due provide snippets of the console output if any errors are encountered.
