### ISSUE TITLE
Don't downloaded the model

### ISSUE THREAD

**Issue by furry72** [Myrkie/BoothDownloader#5]
Hi, when download using this, only downloads the photos and the files no

**Comment by Myrkie** [comment]
did you provide a cookie like the instructions says to? this tool only downloads files you own or files marked as free using your booth token to do so this is not a solution for stealing paid models.

**Comment by furry72** [comment]
i hate pay and more can using my parents money

**Comment by Myrkie** [comment]
this is not the purpose of this project. downloading files without payment is not possible, this only serves as a mean to automatically download __free__ or files you have __paid__ for programmatically, this issue will be closed now.

**Comment by furry72** [comment]
I hope you improve the script, which you can download paid things

**Comment by Myrkie** [comment]
> I hope you improve the script, which you can download paid things

It CAN download paid files only if you __pay__ for them, it is physically impossible to download files you have not paid for from booth as they use AWS authentication tokens for each and every download generated upon requesting the file.
