### ISSUE TITLE
[Feature Request] Resume downloads? Is it possible?

### ISSUE THREAD

**Issue by pato-pan** [Myrkie/BoothDownloader#7]
I was wondering if it could be possible to allow the program to resume downloads instead of deleting it. I tried to look in the files, but I couldn't figure out what it uses to download files, how it does it, or if this is possible.

I am asking because I was having problems downloading my purchase. It was way too slow and it kept failing to download yesterday, both in the browser and also this program. I was using this program hoping it would have this feature, but it doesn't.

Thankfully, it got fixed today. I guess I just had to wait or maybe it's because I set max-retries to 100. Either way, it would be nice if this program had this feature.

**Comment by Myrkie** [comment]
resume downloading is not supported whatever version of AWS they are using doesn't support a range header for file downloads.

Seems more like s2.booth proxies AWS in some way, either way its not standard and doesn't support resuming downloads.
